/*
 * Copyright (c) 2024 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://docs.edgeimpulse.com/page/terms-of-service) or Enterprise Terms of
 * Service (https://docs.edgeimpulse.com/page/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_ANOMALY_METADATA_H_
#define _EI_CLASSIFIER_ANOMALY_METADATA_H_

#include "edge-impulse-sdk/classifier/ei_model_types.h"

const uint16_t ei_classifier_anom_axes[] = { 0, 13, 26 };

// (before - mean) / scale
const float ei_classifier_anom_scale[3] = { 1260.1958705309664, 1410.0195516554, 1803.0880561685572 };
const float ei_classifier_anom_mean[3] = { 1532.6044677363502, 1891.6104055113262, 3722.0523512098525 };
const ei_classifier_anom_cluster_t ei_classifier_anom_clusters[32] = {
	{ ( float[3] ) { -1.131082534790039, -1.2868493795394897, -0.7078012228012085 }, 0.022081882153132608 },
	{ ( float[3] ) { 1.31787109375, 0.41086697578430176, -0.6946738958358765 }, 0.09877153947918099 },
	{ ( float[3] ) { -0.5170088410377502, 1.1545956134796143, 1.251042366027832 }, 0.0544400371548186 },
	{ ( float[3] ) { -0.018760772421956062, 0.8162250518798828, 1.168349266052246 }, 0.01756842740807984 },
	{ ( float[3] ) { 0.03576796501874924, 1.0203452110290527, 1.248183250427246 }, 0.0968663399731817 },
	{ ( float[3] ) { 1.2402360439300537, -0.09629218280315399, -0.7019809484481812 }, 0.08238498324846634 },
	{ ( float[3] ) { 1.0135667324066162, 0.15938164293766022, -0.693394660949707 }, 0.10473837985723286 },
	{ ( float[3] ) { -0.08969826251268387, 1.1944308280944824, 1.3410454988479614 }, 0.12684922941733276 },
	{ ( float[3] ) { -0.2258693426847458, 1.0382026433944702, 1.2305024862289429 }, 0.09873422125007303 },
	{ ( float[3] ) { 1.2988556623458862, 0.06388571858406067, -0.7020441293716431 }, 0.09572866394672916 },
	{ ( float[3] ) { 1.3975801467895508, 0.21238021552562714, -0.6951025724411011 }, 0.08116070119536507 },
	{ ( float[3] ) { 0.11567069590091705, 1.140614628791809, 1.3610495328903198 }, 0.13954530399443238 },
	{ ( float[3] ) { 1.2211726903915405, 0.23112839460372925, -0.6970460414886475 }, 0.0904553074005528 },
	{ ( float[3] ) { 0.22919605672359467, 0.8170246481895447, 1.5803879499435425 }, 0.1437715274230731 },
	{ ( float[3] ) { 1.5148890018463135, 0.13243995606899261, -0.7037206888198853 }, 0.09027814823630458 },
	{ ( float[3] ) { -0.3871248662471771, 1.2816178798675537, 1.321413516998291 }, 0.12934283531135216 },
	{ ( float[3] ) { 1.4470266103744507, -0.048862479627132416, -0.6966970562934875 }, 0.08772094840816887 },
	{ ( float[3] ) { -0.1257314383983612, 1.269943118095398, 1.7181131839752197 }, 0.10389475704736428 },
	{ ( float[3] ) { -0.08941401541233063, 0.981282651424408, 1.4570785760879517 }, 0.10102110619883015 },
	{ ( float[3] ) { -0.22935275733470917, 1.3486757278442383, 1.5006866455078125 }, 0 },
	{ ( float[3] ) { 0.10979403555393219, 1.2169722318649292, 1.5915706157684326 }, 0.10162436793108467 },
	{ ( float[3] ) { 1.0850114822387695, -0.013507891446352005, -0.6956499218940735 }, 0.09549478274535499 },
	{ ( float[3] ) { 1.076655626296997, 0.3702014982700348, -0.6767660975456238 }, 0.08532240301592163 },
	{ ( float[3] ) { -0.38582170009613037, 1.1921583414077759, 1.1693137884140015 }, 0.08608248292370412 },
	{ ( float[3] ) { 0.31085047125816345, 0.950492799282074, 1.7662299871444702 }, 0.09395697896288514 },
	{ ( float[3] ) { -0.4869065582752228, 1.1195876598358154, 1.475559949874878 }, 0.04837913538725734 },
	{ ( float[3] ) { -0.3123417794704437, 1.3001289367675781, 1.7523012161254883 }, 0.09486292397816368 },
	{ ( float[3] ) { -0.5278913974761963, 1.3126050233840942, 1.9566762447357178 }, 0 },
	{ ( float[3] ) { 1.5472255945205688, 0.4074419140815735, -0.6955342292785645 }, 0.07861396264861774 },
	{ ( float[3] ) { -0.26314735412597656, 1.1877105236053467, 1.3586750030517578 }, 0.12029814666081146 },
	{ ( float[3] ) { 0.30043989419937134, 1.1514427661895752, 1.4661163091659546 }, 0.10661129693420954 },
	{ ( float[3] ) { -0.5248827338218689, 0.9343053698539734, 1.057127594947815 }, 0.02517839366364257 },
};

#endif // _EI_CLASSIFIER_ANOMALY_METADATA_H_
