/*
 * Copyright (c) 2024 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://docs.edgeimpulse.com/page/terms-of-service) or Enterprise Terms of
 * Service (https://docs.edgeimpulse.com/page/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_ANOMALY_METADATA_H_
#define _EI_CLASSIFIER_ANOMALY_METADATA_H_

#include "edge-impulse-sdk/classifier/ei_model_types.h"

const uint16_t ei_classifier_anom_axes[] = { 0, 10, 20 };

// (before - mean) / scale
const float ei_classifier_anom_scale[3] = { 1255.5436663534117, 1411.774689901924, 1787.0465947825126 };
const float ei_classifier_anom_mean[3] = { 1530.1823060777451, 1894.0278452488415, 3750.474362378929 };
const ei_classifier_anom_cluster_t ei_classifier_anom_clusters[32] = {
	{ ( float[3] ) { -0.4927022159099579, 1.0916297435760498, 1.4511011838912964 }, 0.11371489803232662 },
	{ ( float[3] ) { -0.13477134704589844, 1.2660150527954102, 1.7319666147232056 }, 0.12459641615037535 },
	{ ( float[3] ) { -1.1318200826644897, -1.286032795906067, -0.7070680260658264 }, 0.02268506801678827 },
	{ ( float[3] ) { 1.3470125198364258, 0.4402604401111603, -0.6931828856468201 }, 0.11414442853098251 },
	{ ( float[3] ) { 1.5170460939407349, 0.36920836567878723, -0.6989600658416748 }, 0.11253714210516871 },
	{ ( float[3] ) { 0.08850333094596863, 1.1092692613601685, 1.28655207157135 }, 0.14782105830707548 },
	{ ( float[3] ) { 0.2598011791706085, 1.159632682800293, 1.4985508918762207 }, 0.17236958823434703 },
	{ ( float[3] ) { 1.2839535474777222, 0.03481036797165871, -0.700115442276001 }, 0.1027634849343602 },
	{ ( float[3] ) { -0.12105590850114822, 1.0079553127288818, 1.466941475868225 }, 0.11104109246747788 },
	{ ( float[3] ) { -0.2509722411632538, 1.0344494581222534, 1.2385153770446777 }, 0.13352884285833597 },
	{ ( float[3] ) { 0.994085967540741, 0.11393848061561584, -0.699116051197052 }, 0.132991971262324 },
	{ ( float[3] ) { -0.24766185879707336, 1.281845211982727, 1.440392017364502 }, 0.09089501709298216 },
	{ ( float[3] ) { 0.027754809707403183, 1.2221579551696777, 1.4993456602096558 }, 0.1484713179377294 },
	{ ( float[3] ) { 1.068471074104309, 0.3140808939933777, -0.6845101118087769 }, 0.1138604411072028 },
	{ ( float[3] ) { 1.652822732925415, 0.23843972384929657, -0.7003507018089294 }, 0.03935939264182061 },
	{ ( float[3] ) { 1.441594123840332, 0.17111068964004517, -0.6973885297775269 }, 0.087495802879297 },
	{ ( float[3] ) { -0.5187159180641174, 1.5213723182678223, 1.9919320344924927 }, 0.08679967491732056 },
	{ ( float[3] ) { -0.4007856249809265, 1.3065420389175415, 1.3331711292266846 }, 0.12737452545107333 },
	{ ( float[3] ) { -0.04815482348203659, 1.116168737411499, 1.411386489868164 }, 0.10241002892119158 },
	{ ( float[3] ) { -0.5153133273124695, 0.9445043802261353, 1.0368953943252563 }, 0.059580837377136216 },
	{ ( float[3] ) { 1.1720871925354004, -0.10667002201080322, -0.7000694274902344 }, 0.14392951347265037 },
	{ ( float[3] ) { -0.46571317315101624, 1.1531026363372803, 1.2198805809020996 }, 0.11516830303736633 },
	{ ( float[3] ) { 1.4845099449157715, -0.019052062183618546, -0.7021202445030212 }, 0.1248180893761417 },
	{ ( float[3] ) { 1.282955527305603, 0.18106545507907867, -0.6930229067802429 }, 0.10149004737246144 },
	{ ( float[3] ) { -0.16194957494735718, 1.1928101778030396, 1.3151438236236572 }, 0.1409192501955703 },
	{ ( float[3] ) { 0.32872283458709717, 0.9808402061462402, 1.9609416723251343 }, 0 },
	{ ( float[3] ) { -0.020622752606868744, 0.8326390981674194, 1.198771595954895 }, 0.030948818875072198 },
	{ ( float[3] ) { -0.24104005098342896, 1.2068638801574707, 1.1870125532150269 }, 1.4901161193847656e-8 },
	{ ( float[3] ) { 1.2723170518875122, 0.30894190073013306, -0.6987465023994446 }, 0.07973209075867109 },
	{ ( float[3] ) { 0.18162518739700317, 0.8123616576194763, 1.5558505058288574 }, 0.11295623327801022 },
	{ ( float[3] ) { 0.31826576590538025, 0.9092702269554138, 1.6208415031433105 }, 0.09269303539859483 },
	{ ( float[3] ) { -0.377548485994339, 1.318747639656067, 1.7753154039382935 }, 0.10032596640154721 },
};

#endif // _EI_CLASSIFIER_ANOMALY_METADATA_H_
